// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group2_CompRepair.Models
{
    public partial class ComputerPart
    {
        public ComputerPart()
        {
            PartsOrdersLinkings = new HashSet<PartsOrdersLinking>();
        }

        public int ComputerPartsId { get; set; }
        public string PartName { get; set; }
        public string PartDescription { get; set; }
        public int? PartsInStock { get; set; }
        public string PartType { get; set; }
        public decimal? PartPrice { get; set; }

        public virtual ICollection<PartsOrdersLinking> PartsOrdersLinkings { get; set; }
    }
}