// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group2_CompRepair.Models
{
    public partial class Order
    {
        public Order()
        {
            PartsOrdersLinkings = new HashSet<PartsOrdersLinking>();
            SoftwareOrdersLinkings = new HashSet<SoftwareOrdersLinking>();
        }

        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public int EmployeeId { get; set; }
        public decimal? OrderTotal { get; set; }
        public DateTime? OrderDate { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<PartsOrdersLinking> PartsOrdersLinkings { get; set; }
        public virtual ICollection<SoftwareOrdersLinking> SoftwareOrdersLinkings { get; set; }
    }
}