// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group2_CompRepair.Models
{
    public partial class SoftwareOrdersLinking
    {
        public int SoftwareOrdersId { get; set; }
        public int OrderId { get; set; }
        public int SoftwareId { get; set; }

        public virtual Order Order { get; set; }
        public virtual Software Software { get; set; }
    }
}