// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group2_CompRepair.Models
{
    public partial class Software
    {
        public Software()
        {
            SoftwareOrdersLinkings = new HashSet<SoftwareOrdersLinking>();
        }

        public int SoftwareId { get; set; }
        public string SoftwareName { get; set; }
        public string SoftwareDescription { get; set; }
        public int? LicensesInStock { get; set; }
        public string SoftwareType { get; set; }
        public decimal? SoftwarePrice { get; set; }

        public virtual ICollection<SoftwareOrdersLinking> SoftwareOrdersLinkings { get; set; }
    }
}